INSERT INTO customer VALUES(1, 'Tom');
INSERT INTO orders VALUES(1, 1);
INSERT INTO ORDER_PRODUCT VALUES(1, 1, 1 ,1);

INSERT INTO ORDER_PRODUCT VALUES(2, 1, 1 ,2);





INSERT INTO customer VALUES(2, 'John');
INSERT INTO orders VALUES(2, 2);
INSERT INTO ORDER_PRODUCT VALUES(3, 1, 2 ,1);

INSERT INTO ORDER_PRODUCT VALUES(4, 1, 2 ,2);


